# Site settings
title:Hello world!!!
email:dbchoi0512@naver.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://eastbean.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:EastBean

# Build settings
markdown: kramdown
remote_theme: creative theme
